sudo: false
language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6'

services:
  - redis-server

script:
  - pip install -r test_requirements.txt
  - pip install pytest-cov codecov
  - py.test --cov ./ .

after_success:
  - codecov
